// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: context.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceID       string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	AppVersion     string                 `protobuf:"bytes,2,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	AppPackageName string                 `protobuf:"bytes,3,opt,name=appPackageName,proto3" json:"appPackageName,omitempty"`
	UserID         string                 `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	SessionID      string                 `protobuf:"bytes,5,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Language       string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	NetworkStatus  string                 `protobuf:"bytes,7,opt,name=networkStatus,proto3" json:"networkStatus,omitempty"`
	Location       string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	IpAddress      string                 `protobuf:"bytes,9,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	IsRooted       bool                   `protobuf:"varint,10,opt,name=isRooted,proto3" json:"isRooted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *Context) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Context) GetAppPackageName() string {
	if x != nil {
		return x.AppPackageName
	}
	return ""
}

func (x *Context) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Context) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Context) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Context) GetNetworkStatus() string {
	if x != nil {
		return x.NetworkStatus
	}
	return ""
}

func (x *Context) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Context) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Context) GetIsRooted() bool {
	if x != nil {
		return x.IsRooted
	}
	return false
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_context_proto protoreflect.FileDescriptor

const file_context_proto_rawDesc = "" +
	"\n" +
	"\rcontext.proto\x12\x03log\"\xbb\x02\n" +
	"\aContext\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x02 \x01(\tR\n" +
	"appVersion\x12&\n" +
	"\x0eappPackageName\x18\x03 \x01(\tR\x0eappPackageName\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\x12\x1c\n" +
	"\tsessionID\x18\x05 \x01(\tR\tsessionID\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12$\n" +
	"\rnetworkStatus\x18\a \x01(\tR\rnetworkStatus\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1c\n" +
	"\tipAddress\x18\t \x01(\tR\tipAddress\x12\x1a\n" +
	"\bisRooted\x18\n" +
	" \x01(\bR\bisRooted\">\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2<\n" +
	"\x0eContextService\x12*\n" +
	"\vSendContext\x12\f.log.Context\x1a\r.log.ResponseB(Z&go-grpc-server/internal/grpc/proto;logb\x06proto3"

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData []byte
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)))
	})
	return file_context_proto_rawDescData
}

var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_context_proto_goTypes = []any{
	(*Context)(nil),  // 0: log.Context
	(*Response)(nil), // 1: log.Response
}
var file_context_proto_depIdxs = []int32{
	0, // 0: log.ContextService.SendContext:input_type -> log.Context
	1, // 1: log.ContextService.SendContext:output_type -> log.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
