// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/grpc/proto/event.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventMessage        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_internal_grpc_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventList) GetEvents() []*EventMessage {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EventID              string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	EventName            string                 `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	ScreenName           string                 `protobuf:"bytes,4,opt,name=screenName,proto3" json:"screenName,omitempty"`
	EventTime            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	AppOpened            bool                   `protobuf:"varint,6,opt,name=appOpened,proto3" json:"appOpened,omitempty"`
	AppBackgrounded      bool                   `protobuf:"varint,7,opt,name=appBackgrounded,proto3" json:"appBackgrounded,omitempty"`
	SessionStarted       bool                   `protobuf:"varint,8,opt,name=sessionStarted,proto3" json:"sessionStarted,omitempty"`
	SessionEnded         bool                   `protobuf:"varint,9,opt,name=sessionEnded,proto3" json:"sessionEnded,omitempty"`
	Latitude             float64                `protobuf:"fixed64,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64                `protobuf:"fixed64,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	City                 string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	Region               string                 `protobuf:"bytes,13,opt,name=region,proto3" json:"region,omitempty"`
	Country              string                 `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	Carrier              string                 `protobuf:"bytes,15,opt,name=carrier,proto3" json:"carrier,omitempty"`
	DynamicConfigChanged bool                   `protobuf:"varint,16,opt,name=dynamicConfigChanged,proto3" json:"dynamicConfigChanged,omitempty"`
	CustomAttributes     map[string]string      `protobuf:"bytes,17,rep,name=customAttributes,proto3" json:"customAttributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_internal_grpc_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventMessage) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *EventMessage) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventMessage) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *EventMessage) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *EventMessage) GetAppOpened() bool {
	if x != nil {
		return x.AppOpened
	}
	return false
}

func (x *EventMessage) GetAppBackgrounded() bool {
	if x != nil {
		return x.AppBackgrounded
	}
	return false
}

func (x *EventMessage) GetSessionStarted() bool {
	if x != nil {
		return x.SessionStarted
	}
	return false
}

func (x *EventMessage) GetSessionEnded() bool {
	if x != nil {
		return x.SessionEnded
	}
	return false
}

func (x *EventMessage) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EventMessage) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EventMessage) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EventMessage) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *EventMessage) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *EventMessage) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *EventMessage) GetDynamicConfigChanged() bool {
	if x != nil {
		return x.DynamicConfigChanged
	}
	return false
}

func (x *EventMessage) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

type EventFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=fileContent,proto3" json:"fileContent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFileRequest) Reset() {
	*x = EventFileRequest{}
	mi := &file_internal_grpc_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFileRequest) ProtoMessage() {}

func (x *EventFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFileRequest.ProtoReflect.Descriptor instead.
func (*EventFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventFileRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *EventFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *EventFileRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

var File_internal_grpc_proto_event_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpc/proto/event.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!internal/grpc/proto/context.proto\"6\n" +
	"\tEventList\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.log.EventMessageR\x06events\"\x9c\x05\n" +
	"\fEventMessage\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x1c\n" +
	"\teventName\x18\x03 \x01(\tR\teventName\x12\x1e\n" +
	"\n" +
	"screenName\x18\x04 \x01(\tR\n" +
	"screenName\x128\n" +
	"\teventTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x1c\n" +
	"\tappOpened\x18\x06 \x01(\bR\tappOpened\x12(\n" +
	"\x0fappBackgrounded\x18\a \x01(\bR\x0fappBackgrounded\x12&\n" +
	"\x0esessionStarted\x18\b \x01(\bR\x0esessionStarted\x12\"\n" +
	"\fsessionEnded\x18\t \x01(\bR\fsessionEnded\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\r \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x0e \x01(\tR\acountry\x12\x18\n" +
	"\acarrier\x18\x0f \x01(\tR\acarrier\x122\n" +
	"\x14dynamicConfigChanged\x18\x10 \x01(\bR\x14dynamicConfigChanged\x12S\n" +
	"\x10customAttributes\x18\x11 \x03(\v2'.log.EventMessage.CustomAttributesEntryR\x10customAttributes\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x10EventFileRequest\x12\x1c\n" +
	"\tsessionID\x18\x01 \x01(\tR\tsessionID\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12 \n" +
	"\vfileContent\x18\x03 \x01(\fR\vfileContent2\xa4\x01\n" +
	"\fEventService\x12-\n" +
	"\tSendEvent\x12\x11.log.EventMessage\x1a\r.log.Response\x12.\n" +
	"\rSendEventList\x12\x0e.log.EventList\x1a\r.log.Response\x125\n" +
	"\rSendEventFile\x12\x15.log.EventFileRequest\x1a\r.log.ResponseB(Z&go-grpc-server/internal/grpc/proto;logb\x06proto3"

var (
	file_internal_grpc_proto_event_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_event_proto_rawDescData []byte
)

func file_internal_grpc_proto_event_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_event_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_event_proto_rawDesc), len(file_internal_grpc_proto_event_proto_rawDesc)))
	})
	return file_internal_grpc_proto_event_proto_rawDescData
}

var file_internal_grpc_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpc_proto_event_proto_goTypes = []any{
	(*EventList)(nil),             // 0: log.EventList
	(*EventMessage)(nil),          // 1: log.EventMessage
	(*EventFileRequest)(nil),      // 2: log.EventFileRequest
	nil,                           // 3: log.EventMessage.CustomAttributesEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Response)(nil),              // 5: log.Response
}
var file_internal_grpc_proto_event_proto_depIdxs = []int32{
	1, // 0: log.EventList.events:type_name -> log.EventMessage
	4, // 1: log.EventMessage.eventTime:type_name -> google.protobuf.Timestamp
	3, // 2: log.EventMessage.customAttributes:type_name -> log.EventMessage.CustomAttributesEntry
	1, // 3: log.EventService.SendEvent:input_type -> log.EventMessage
	0, // 4: log.EventService.SendEventList:input_type -> log.EventList
	2, // 5: log.EventService.SendEventFile:input_type -> log.EventFileRequest
	5, // 6: log.EventService.SendEvent:output_type -> log.Response
	5, // 7: log.EventService.SendEventList:output_type -> log.Response
	5, // 8: log.EventService.SendEventFile:output_type -> log.Response
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_event_proto_init() }
func file_internal_grpc_proto_event_proto_init() {
	if File_internal_grpc_proto_event_proto != nil {
		return
	}
	file_internal_grpc_proto_context_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_event_proto_rawDesc), len(file_internal_grpc_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_event_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_event_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_event_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_event_proto = out.File
	file_internal_grpc_proto_event_proto_goTypes = nil
	file_internal_grpc_proto_event_proto_depIdxs = nil
}
