// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: log.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_DEBUG LogLevel = 0
	LogLevel_INFO  LogLevel = 1
	LogLevel_WARN  LogLevel = 2
	LogLevel_ERROR LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"DEBUG": 0,
		"INFO":  1,
		"WARN":  2,
		"ERROR": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

type LogType int32

const (
	LogType_UNKNOWN     LogType = 0
	LogType_NON_FATAL   LogType = 1
	LogType_FATAL_CRASH LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NON_FATAL",
		2: "FATAL_CRASH",
	}
	LogType_value = map[string]int32{
		"UNKNOWN":     0,
		"NON_FATAL":   1,
		"FATAL_CRASH": 2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_log_proto_enumTypes[1].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_log_proto_enumTypes[1]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

type LogMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogID           string                 `protobuf:"bytes,1,opt,name=logID,proto3" json:"logID,omitempty"`
	Level           LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=log.LogLevel" json:"level,omitempty"`
	Type            LogType                `protobuf:"varint,4,opt,name=type,proto3,enum=log.LogType" json:"type,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace      string                 `protobuf:"bytes,6,opt,name=stackTrace,proto3" json:"stackTrace,omitempty"`
	SessionID       string                 `protobuf:"bytes,7,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	LoggedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=loggedAt,proto3" json:"loggedAt,omitempty"`
	FreeRAMMB       float64                `protobuf:"fixed64,9,opt,name=freeRAMMB,proto3" json:"freeRAMMB,omitempty"`
	FreeStorageMB   float64                `protobuf:"fixed64,10,opt,name=freeStorageMB,proto3" json:"freeStorageMB,omitempty"`
	DeviceModel     string                 `protobuf:"bytes,11,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	DeviceOS        string                 `protobuf:"bytes,12,opt,name=deviceOS,proto3" json:"deviceOS,omitempty"`
	DeviceOSVersion string                 `protobuf:"bytes,13,opt,name=deviceOSVersion,proto3" json:"deviceOSVersion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogMessage) GetLogID() string {
	if x != nil {
		return x.LogID
	}
	return ""
}

func (x *LogMessage) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogMessage) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_UNKNOWN
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *LogMessage) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *LogMessage) GetLoggedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoggedAt
	}
	return nil
}

func (x *LogMessage) GetFreeRAMMB() float64 {
	if x != nil {
		return x.FreeRAMMB
	}
	return 0
}

func (x *LogMessage) GetFreeStorageMB() float64 {
	if x != nil {
		return x.FreeStorageMB
	}
	return 0
}

func (x *LogMessage) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *LogMessage) GetDeviceOS() string {
	if x != nil {
		return x.DeviceOS
	}
	return ""
}

func (x *LogMessage) GetDeviceOSVersion() string {
	if x != nil {
		return x.DeviceOSVersion
	}
	return ""
}

var File_log_proto protoreflect.FileDescriptor

const file_log_proto_rawDesc = "" +
	"\n" +
	"\tlog.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rcontext.proto\"\xa5\x03\n" +
	"\n" +
	"LogMessage\x12\x14\n" +
	"\x05logID\x18\x01 \x01(\tR\x05logID\x12#\n" +
	"\x05level\x18\x03 \x01(\x0e2\r.log.LogLevelR\x05level\x12 \n" +
	"\x04type\x18\x04 \x01(\x0e2\f.log.LogTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"stackTrace\x18\x06 \x01(\tR\n" +
	"stackTrace\x12\x1c\n" +
	"\tsessionID\x18\a \x01(\tR\tsessionID\x126\n" +
	"\bloggedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bloggedAt\x12\x1c\n" +
	"\tfreeRAMMB\x18\t \x01(\x01R\tfreeRAMMB\x12$\n" +
	"\rfreeStorageMB\x18\n" +
	" \x01(\x01R\rfreeStorageMB\x12 \n" +
	"\vdeviceModel\x18\v \x01(\tR\vdeviceModel\x12\x1a\n" +
	"\bdeviceOS\x18\f \x01(\tR\bdeviceOS\x12(\n" +
	"\x0fdeviceOSVersion\x18\r \x01(\tR\x0fdeviceOSVersion*4\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*6\n" +
	"\aLogType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tNON_FATAL\x10\x01\x12\x0f\n" +
	"\vFATAL_CRASH\x10\x0227\n" +
	"\n" +
	"LogService\x12)\n" +
	"\aSendLog\x12\x0f.log.LogMessage\x1a\r.log.ResponseB(Z&go-grpc-server/internal/grpc/proto;logb\x06proto3"

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData []byte
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)))
	})
	return file_log_proto_rawDescData
}

var file_log_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_log_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: log.LogLevel
	(LogType)(0),                  // 1: log.LogType
	(*LogMessage)(nil),            // 2: log.LogMessage
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Response)(nil),              // 4: log.Response
}
var file_log_proto_depIdxs = []int32{
	0, // 0: log.LogMessage.level:type_name -> log.LogLevel
	1, // 1: log.LogMessage.type:type_name -> log.LogType
	3, // 2: log.LogMessage.loggedAt:type_name -> google.protobuf.Timestamp
	2, // 3: log.LogService.SendLog:input_type -> log.LogMessage
	4, // 4: log.LogService.SendLog:output_type -> log.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	file_context_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		EnumInfos:         file_log_proto_enumTypes,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
