// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for log levels
type LogLevel int32

const (
	LogLevel_VERBOSE LogLevel = 0
	LogLevel_DEBUG   LogLevel = 1
	LogLevel_INFO    LogLevel = 2
	LogLevel_WARN    LogLevel = 3
	LogLevel_ERROR   LogLevel = 4
	LogLevel_FATAL   LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "VERBOSE",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
		5: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"VERBOSE": 0,
		"DEBUG":   1,
		"INFO":    2,
		"WARN":    3,
		"ERROR":   4,
		"FATAL":   5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

// LogEvent message definition
type LogEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	LogID    string                 `protobuf:"bytes,1,opt,name=logID,proto3" json:"logID,omitempty"`       // Unique log ID, could be UUID
	Mnemonic string                 `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"` // Short identifier (optional purpose marker)
	// Device Info
	DeviceID        string `protobuf:"bytes,3,opt,name=deviceID,proto3" json:"deviceID,omitempty"`               // Device ID
	DeviceName      string `protobuf:"bytes,4,opt,name=deviceName,proto3" json:"deviceName,omitempty"`           // Device Name
	DeviceModel     string `protobuf:"bytes,5,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`         // Device Model
	DeviceOS        string `protobuf:"bytes,6,opt,name=deviceOS,proto3" json:"deviceOS,omitempty"`               // Device OS
	DeviceOSVersion string `protobuf:"bytes,7,opt,name=deviceOSVersion,proto3" json:"deviceOSVersion,omitempty"` // Device OS Version
	// App Info
	AppVersion     string `protobuf:"bytes,8,opt,name=appVersion,proto3" json:"appVersion,omitempty"`          // App Version
	AppName        string `protobuf:"bytes,9,opt,name=appName,proto3" json:"appName,omitempty"`                // App Name
	AppPackageName string `protobuf:"bytes,10,opt,name=appPackageName,proto3" json:"appPackageName,omitempty"` // App Package Name
	// Log Content
	LogMessage string   `protobuf:"bytes,11,opt,name=logMessage,proto3" json:"logMessage,omitempty"`                // Log Message
	LogLevel   LogLevel `protobuf:"varint,12,opt,name=logLevel,proto3,enum=log.LogLevel" json:"logLevel,omitempty"` // Log Level
	StackTrace string   `protobuf:"bytes,13,opt,name=stackTrace,proto3" json:"stackTrace,omitempty"`                // Stack Trace (optional)
	// Metadata
	TimeStamp     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`         // Timestamp of the event
	SessionID     string                 `protobuf:"bytes,15,opt,name=sessionID,proto3" json:"sessionID,omitempty"`         // Session ID
	UserID        string                 `protobuf:"bytes,16,opt,name=userID,proto3" json:"userID,omitempty"`               // User ID
	NetworkStatus string                 `protobuf:"bytes,17,opt,name=networkStatus,proto3" json:"networkStatus,omitempty"` // Network Status (e.g., "Online", "Offline")
	Location      string                 `protobuf:"bytes,18,opt,name=location,proto3" json:"location,omitempty"`           // Location (e.g., "New York", "San Francisco")
	// Custom fields for extensibility
	CustomAttributes map[string]string `protobuf:"bytes,19,rep,name=customAttributes,proto3" json:"customAttributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom key-value attributes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetLogID() string {
	if x != nil {
		return x.LogID
	}
	return ""
}

func (x *LogEvent) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *LogEvent) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *LogEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *LogEvent) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *LogEvent) GetDeviceOS() string {
	if x != nil {
		return x.DeviceOS
	}
	return ""
}

func (x *LogEvent) GetDeviceOSVersion() string {
	if x != nil {
		return x.DeviceOSVersion
	}
	return ""
}

func (x *LogEvent) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *LogEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *LogEvent) GetAppPackageName() string {
	if x != nil {
		return x.AppPackageName
	}
	return ""
}

func (x *LogEvent) GetLogMessage() string {
	if x != nil {
		return x.LogMessage
	}
	return ""
}

func (x *LogEvent) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_VERBOSE
}

func (x *LogEvent) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *LogEvent) GetTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *LogEvent) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *LogEvent) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LogEvent) GetNetworkStatus() string {
	if x != nil {
		return x.NetworkStatus
	}
	return ""
}

func (x *LogEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LogEvent) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

// LogResponse message definition
type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicates whether the log was successfully processed
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Additional information (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_log_proto protoreflect.FileDescriptor

const file_log_proto_rawDesc = "" +
	"\n" +
	"\tlog.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x05\n" +
	"\bLogEvent\x12\x14\n" +
	"\x05logID\x18\x01 \x01(\tR\x05logID\x12\x1a\n" +
	"\bmnemonic\x18\x02 \x01(\tR\bmnemonic\x12\x1a\n" +
	"\bdeviceID\x18\x03 \x01(\tR\bdeviceID\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x04 \x01(\tR\n" +
	"deviceName\x12 \n" +
	"\vdeviceModel\x18\x05 \x01(\tR\vdeviceModel\x12\x1a\n" +
	"\bdeviceOS\x18\x06 \x01(\tR\bdeviceOS\x12(\n" +
	"\x0fdeviceOSVersion\x18\a \x01(\tR\x0fdeviceOSVersion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\b \x01(\tR\n" +
	"appVersion\x12\x18\n" +
	"\aappName\x18\t \x01(\tR\aappName\x12&\n" +
	"\x0eappPackageName\x18\n" +
	" \x01(\tR\x0eappPackageName\x12\x1e\n" +
	"\n" +
	"logMessage\x18\v \x01(\tR\n" +
	"logMessage\x12)\n" +
	"\blogLevel\x18\f \x01(\x0e2\r.log.LogLevelR\blogLevel\x12\x1e\n" +
	"\n" +
	"stackTrace\x18\r \x01(\tR\n" +
	"stackTrace\x128\n" +
	"\ttimeStamp\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStamp\x12\x1c\n" +
	"\tsessionID\x18\x0f \x01(\tR\tsessionID\x12\x16\n" +
	"\x06userID\x18\x10 \x01(\tR\x06userID\x12$\n" +
	"\rnetworkStatus\x18\x11 \x01(\tR\rnetworkStatus\x12\x1a\n" +
	"\blocation\x18\x12 \x01(\tR\blocation\x12O\n" +
	"\x10customAttributes\x18\x13 \x03(\v2#.log.LogEvent.CustomAttributesEntryR\x10customAttributes\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*L\n" +
	"\bLogLevel\x12\v\n" +
	"\aVERBOSE\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\t\n" +
	"\x05FATAL\x10\x052:\n" +
	"\n" +
	"LogService\x12,\n" +
	"\tUploadLog\x12\r.log.LogEvent\x1a\x10.log.LogResponseBXZVgithub.com/adarsh-devappsys/go-grpc-server/grpc-kafka-server/internal/grpc/proto;protob\x06proto3"

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData []byte
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)))
	})
	return file_log_proto_rawDescData
}

var file_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_log_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: log.LogLevel
	(*LogEvent)(nil),              // 1: log.LogEvent
	(*LogResponse)(nil),           // 2: log.LogResponse
	nil,                           // 3: log.LogEvent.CustomAttributesEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_log_proto_depIdxs = []int32{
	0, // 0: log.LogEvent.logLevel:type_name -> log.LogLevel
	4, // 1: log.LogEvent.timeStamp:type_name -> google.protobuf.Timestamp
	3, // 2: log.LogEvent.customAttributes:type_name -> log.LogEvent.CustomAttributesEntry
	1, // 3: log.LogService.UploadLog:input_type -> log.LogEvent
	2, // 4: log.LogService.UploadLog:output_type -> log.LogResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		EnumInfos:         file_log_proto_enumTypes,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
